:Author: ed84c
:Email: efkhunt@gmail.com
:Date: 04/06/2017
:Revision: version#
:License: Public Domain

= Project: ‘EdLights

Light randomiser. This is a trivial and largely pointless project. It is unlikely to be a panacea of contentment.

== Step 1: Installation
Put on your arduino and then run it.

== Step 2: Assemble the circuit
Im doing this with the Ikea usb lights plugged into the GPIO ports. They should draw around 30mA so OK. Do not plug in anything that draws more than 40mA/ port else the arduin o will blow up and your house will burn.

=== License
This project is released under a Eds Discount Licenses License.

=== Contributing
To contribute to this project please contact ed84c <efkhunt@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
